/** Data for the Book a Service form: select option lists and furniture inventory. */

export const propertySizeOptions = [
  "1 bedroom: up to 400 cubic feet",
  "2 bedroom: 401 up to 700 cubic feet",
  "3 bedroom: 701 up to 1 200 cubic feet",
  "4 bedroom: 1 201 up to 1 900 cubic feet",
  "5 bedroom: 1 901 up to 2 200 cubic feet",
  "6 bedroom: 2 200 up to * cubic feet",
  "Office",
  "Other",
];

export const floorOptions = ["Ground", "1", "2", "3+"];

export const whereOptions = [
  "Google",
  "Other search engine",
  "Estate Agent",
  "Leaflet/Letter",
  "Magazine",
  "Internet directory",
  "Removals Nationwide Vehicle",
  "Recommendation",
  "I've used Removals Nationwide before",
  "Other",
];

export const removalOptions = [
  "Parking pick up",
  "Packing required",
  "Reassembling",
  "Parking delivery",
  "Boxes required",
  "Cleaning",
];

const kitchen = [
  "Cooker 18",
  "Microwave",
  "Freezer upright",
  "Freezer chest",
  "Fridge Freezer",
  "Refrigerator- small",
  "Refrigerator",
  "Refrigerator- large (American style)",
  "Washing Machine",
  "Washer and Dryer",
  "Dryer",
  "Vacuum Cleaner",
  "Electric Floor Polisher",
  "Dishwasher",
  "Kitchen Cabinet",
  "Kitchen Table - large",
  "Kitchen Table - small",
  "Kitchen Chair",
  "Baby's High Chair",
  "Tea Trolley",
  "Store Cupboard - medium",
  "Hand Sewing Machine",
  "Hall Table",
  "Hall Stand",
  "Hall chair",
  "Clothes Horse",
  "Safe (state make & weight)",
];

// Living room and Dining room share this same list.
const livingRoom = [
  "3 Seater Settee",
  "2 Seater Settee",
  "Armchair",
  "Rocking chair",
  "Tub Armchair - Small",
  "Occasional Chair",
  "Wall Unit",
  "China Cabinet - large",
  "China Cabinet - small",
  "China Cabinet - medium",
  "Welsh Dresser",
  "Sideboard - large",
  "Sideboard - medium",
  "Sideboard - small",
  "Dining Table - large",
  "Dining Table - medium",
  "Dining Table - small",
  "Occasional Table - small",
  "Dining chair",
  "Carver",
  "Roll-top Desk - large",
  "Roll-top Desk - small",
  "Bureau - large",
  "Bureau - small",
  "Bookcase - large",
  "Bookcase - small",
  "Bookshelf (per shelf)",
  "Grandfather Clock",
  "Chandelier",
  "Standard Lamp",
  "Carpet - fitted",
  "Rug - medium",
  "Piano - upright",
  "Piano - Miniature",
  "Piano - Player",
  "Piano Baby Grand",
  "Piano Boudoir Grand",
  "Piano Stool",
  "Hi-fi system",
  "Floor Standing Speakers",
  "CD Stand",
  "T.V.",
  "Video / DVD Player",
  "Nest Tables",
  "Music Cabinet",
  "Stool",
  "Mirror",
  "Coffee Table",
  "Picture",
];

const bedroom = [
  "Wardrobe 6′6″ (width)",
  "Wardrobe 4′6″ (width)",
  "Wardrobe 3′0″ (width)",
  "Wardrobe 2′6″ (width)",
  "Home Computer",
  "Dressing Table",
  "Dressing Table",
  "Chest of Drawers. Large",
  "Chest of Drawers - Medium",
  "Chest of Drawers - Small",
  "Chest of Drawers - Bow fronted",
  "Tallboy normal",
  "Blanket Box",
  "Folding Bed",
  "Sofa Bed",
  "Bedroom Chair",
  "Cot",
  "Bedstead 5'",
  "Bedstead 4'",
  "Bedstead 3'",
  "Bunk Beds",
  "Continental Headboard",
  "Pedestal Cupboard",
  "Childs Folding Cot",
  "Bedside Table",
  "Box Ottoman",
  "Linen Basket",
  "Table Lamp",
];

const garden = [
  "Garden Roller",
  "Wheelbarrow",
  "Lawn Mower - normal",
  "Lawn Mower - ride on",
  "Barbeque",
  "Sun - Lounger",
  "Hose and Reel",
  "Garden Tool - per tool",
  "Dustbin - normal",
  "Pair Steps",
  "Garden table",
  "Garden Chairs (Stackable)",
  "Pram/Pushchair",
  "Extensions Ladder",
  "Deck Chairs",
  "Work Bench",
  "Plant Pots",
  "Plants",
  "Golf Clubs",
  "Bicycle",
  "Folding Chairs",
  "Office Desk",
  "Office Chair",
  "Kitchen Bin",
  "Brooms/Mop",
  "Wine (box)",
  "Storage Boxes (large plastic)",
  "Storage Boxes (small Plastic)",
];

export type FurnitureCategory = { name: string; options: string[] };

export const furnitureCategories: FurnitureCategory[] = [
  { name: "Kitchen", options: kitchen },
  { name: "Living room", options: livingRoom },
  { name: "Bedroom", options: bedroom },
  { name: "Dining room", options: livingRoom },
  { name: "Garden", options: garden },
];
