import Link from "next/link";
import { PageHeading, StatusBadge, money, shortDate } from "@/components/admin/AdminPrimitives";
import { filterBookingsByRange } from "@/lib/admin-dashboard";
import { bookingRoute, getBookings, moveStatus } from "@/lib/bookings";

export const dynamic = "force-dynamic";

const iso = (date: Date) => date.toISOString().slice(0, 10);

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string; tab?: string }> }) {
  const [bookings, query] = await Promise.all([getBookings(), searchParams]);
  const tab = query.tab === "leads" ? "leads" : "financials";
  const rows = filterBookingsByRange(bookings, query.from || "", query.to || "");
  const completed = rows.filter((booking) => moveStatus(booking.status) === "Completed");
  const revenue = completed.reduce((sum, booking) => sum + Number(booking.quote || 0), 0);
  const expenses = completed.reduce((sum, booking) => sum + Number(booking.expenses || 0), 0);
  const abandoned = rows.filter((booking) => moveStatus(booking.status) === "Abandoned").length;
  const now = new Date(); const thisMonthFrom = `${iso(now).slice(0, 7)}-01`;
  const lastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1); const lastMonthEnd = new Date(now.getFullYear(), now.getMonth(), 0);
  const href = (nextTab: string) => `/admin/reports?tab=${nextTab}&from=${query.from || ""}&to=${query.to || ""}`;
  return <div className="mx-auto max-w-[1500px]"><PageHeading title="Reports" subtitle="Revenue, costs, profit and lead performance." />
    <section className="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><form className="flex flex-wrap items-end gap-3"><input type="hidden" name="tab" value={tab} /><label className="text-xs font-bold uppercase text-slate-500">From<input name="from" type="date" defaultValue={query.from} className="mt-1 block rounded-xl border border-slate-200 px-3 py-2 text-sm" /></label><label className="text-xs font-bold uppercase text-slate-500">To<input name="to" type="date" defaultValue={query.to} className="mt-1 block rounded-xl border border-slate-200 px-3 py-2 text-sm" /></label><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Apply</button><span className="h-8 w-px bg-slate-200" /><Link className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold" href={`/admin/reports?tab=${tab}&from=${thisMonthFrom}&to=${iso(now)}`}>This Month</Link><Link className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold" href={`/admin/reports?tab=${tab}&from=${iso(lastMonth)}&to=${iso(lastMonthEnd)}`}>Last Month</Link><Link className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold" href={`/admin/reports?tab=${tab}`}>All Time</Link></form></section>
    <div className="mt-6 flex gap-2"><Link href={href("financials")} className={`rounded-full px-4 py-2 text-sm font-semibold ${tab === "financials" ? "bg-slate-950 text-white" : "bg-white text-slate-600"}`}>Financials</Link><Link href={href("leads")} className={`rounded-full px-4 py-2 text-sm font-semibold ${tab === "leads" ? "bg-slate-950 text-white" : "bg-white text-slate-600"}`}>Leads</Link></div>
    {tab === "financials" ? <><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total Revenue", money(revenue), "Completed work"],["Total Expenses", money(expenses), "Recorded costs"],["Net Profit", money(revenue-expenses), "Revenue minus expenses"],["Avg Job Value", money(completed.length ? revenue/completed.length : 0), "Per completed move"]].map(([label,value,caption], index) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="text-xl">{["£","−","↗","÷"][index]}</span><p className="mt-6 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-400">{caption}</p></article>)}</div><ReportTable title="Completed Jobs Breakdown" headings={["Customer","Route","Date","Revenue","Expenses","Profit"]}>{completed.map((booking) => { const route=bookingRoute(booking); return <tr key={booking.id}><Cell strong>{booking.full_name}</Cell><Cell>{route.from} → {route.to}</Cell><Cell>{shortDate(booking.move_date)}</Cell><Cell>{money(booking.quote)}</Cell><Cell>{money(booking.expenses)}</Cell><Cell strong>{money(booking.quote-booking.expenses)}</Cell></tr>; })}</ReportTable></> : <><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Total Leads",rows.length],["New",rows.filter(b=>moveStatus(b.status)==="New").length],["Completed",completed.length],["Abandoned",abandoned],["Conversion %",`${rows.length ? Math.round(completed.length/rows.length*100) : 0}%`]].map(([label,value]) => <article key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></article>)}</div><ReportTable title="All Leads Breakdown" headings={["Customer","Contact","Type","Route","Status","Created"]}>{rows.map((booking)=>{const route=bookingRoute(booking); return <tr key={booking.id}><Cell strong>{booking.full_name}</Cell><Cell>{booking.phone}<br/><span className="text-xs">{booking.email}</span></Cell><Cell>{booking.move_type}</Cell><Cell>{route.from} → {route.to}</Cell><Cell><StatusBadge status={moveStatus(booking.status)} /></Cell><Cell>{shortDate(booking.created_at.slice(0,10))}</Cell></tr>;})}</ReportTable></>}
  </div>;
}

function Cell({ children, strong=false }: { children: React.ReactNode; strong?: boolean }) { return <td className={`px-5 py-4 text-sm text-slate-600 ${strong ? "font-semibold text-slate-900" : ""}`}>{children}</td>; }
function ReportTable({ title, headings, children }: { title: string; headings: string[]; children: React.ReactNode }) { return <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><h2 className="border-b border-slate-100 px-5 py-4 font-bold">{title}</h2><div className="overflow-x-auto"><table className="min-w-[800px] w-full text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{headings.map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{children}</tbody></table></div></section>; }
